### ISSUE TITLE
Some text is difficult to read

### ISSUE THREAD

**Issue by stvnrlly** [codefordc/opendatadc#26]
- I sometimes find red text on a blue background to be difficult to read
- For whatever reason, it's difficult to make out the letters that have a white border

<img width="583" alt="screen shot 2017-01-10 at 12 11 12 pm" src="https://cloud.githubusercontent.com/assets/4156602/21816409/11f49e86-d72e-11e6-82ff-5f02b8ccbc98.png">

**Comment by mkalish** [comment]
I'm terrible with colors, but I've removed some of the most offensive color choices and the outlines.
<img width="1149" alt="screen shot 2017-01-10 at 10 32 15 pm" src="https://cloud.githubusercontent.com/assets/1225895/21834645/c0928786-d784-11e6-8ac4-c390b716daf7.png">

**Comment by stvnrlly** [comment]
Nice, that's an improvement for sure.

It can be helpful to outsource color contrast stuff to accessibility standards: [HTML CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) is a great tool for that. With a quick scan, it looks like it thinks that there are still some contrast improvements to be made.
