### ISSUE TITLE
Geo data maps

### ISSUE THREAD

**Issue by mkalish** [codefordc/opendatadc#33]
This fall Mapquest (I know, I know) removed their public tilesets.  This ticket would involve choosing and applying a new tileset to the geojson datasets.

Tasks:
* Double check that geojson plugin is installed in CKAN
* Choose a new tile set (I've looked at mapbox)
* Get the tiles working locally (update the develop.ini file)
* Update the production.ini file on the prod box

**Comment by jalbertbowden** [comment]
i'm going to work on this

**Comment by jalbertbowden** [comment]
example of gis rendering on the portal. when tiles are fixed, this page should be pretty:
http://data.codefordc.org/dataset/34cc3e71-2055-4631-81fc-2cfa61256861/resource/cf07e890-39c3-4c15-a35e-4987fc48932e
