### ISSUE TITLE
Add datarequests to the menu bar

### ISSUE THREAD

**Issue by mkalish** [codefordc/opendatadc#43]
We are trying to promote the data requests feature of the site, but there is only one link to it on the home page.  It should also exist as a link in the menu bar

Tasks
* Update the menu template and a link to the data requests page `http://data.codefordc.org/datarequest`

**Comment by GUITARPLRC** [comment]
Can I help out on this?

**Comment by mkalish** [comment]
Absolutely, let me know if you run into any issues getting setup

**Comment by GUITARPLRC** [comment]
I would love to help out but, I think I am in over my head, I didn't thoroughly look at the project and code, I thought it was just some HTML that needed to be updated. Sorry to waste your time. I will delete my comments... unless you'd like to to give me some pointers, but then you could probably do it yourself

**Comment by mkalish** [comment]
So it is mostly just small HTML changes that need to be made.  I can walk you through the initial setup at the next meetup and save this ticket for you if you like.  I promise the setup seems more daunting than it really is,

**Comment by GUITARPLRC** [comment]
on second thought I can't even get docker working on my machine, better let some else have at it.... sorry
