### ISSUE TITLE
set up google analytics or equivalent

### ISSUE THREAD

**Issue by mattbailey0** [codefordc/opendatadc#6]
@mkalish - is this already done?

**Comment by mkalish** [comment]
@mattbailey0 
Not yet, I'll go ahead and create the tag and install [this](https://github.com/ckan/ckanext-googleanalytics) tonight/tomorrow

**Comment by mattbailey0** [comment]
@mkalish you are a dream

**Comment by mkalish** [comment]
Google analytics was added this morning and I turned on the [stats](http://data.codefordc.org/stats) page for CKAN itself.

@mattbailey0 let me know what email address I should add as a user for the analytics account
