### ISSUE TITLE
Datarequests link does direct to the right spot

### ISSUE THREAD

**Issue by mkalish** [codefordc/opendatadc#71]
<img width="519" alt="screen shot 2018-08-20 at 6 58 51 pm" src="https://user-images.githubusercontent.com/1225895/44371081-1b594c00-a4ab-11e8-966d-e76c7d04dc03.png">
The Data requests tab redirects to `http://data.codefordc.org/datarequests` when it should direct to `http://data.codefordc.org/datarequest`

**Comment by discdiver** [comment]
Working on this.

**Comment by mo-oneill** [comment]
Just checked out the website and the link is directing to the correct place. This issue should be closed.
